development:
  stripe_secret_key: 'sk_test_W6dVw2Tjuqnrn3sxc8MtilAo00hziH4J8s'
  stripe_publishable_key: 'pk_test_X6Plm3E7APBJNPKv3dT5JiGl00gzC4vnDg'

production:
  stripe_secret_key: ''
  stripe_publishable_key: ''